name: Qt CI

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          # В Ubuntu 24.04 пакет libasound2 заменен на libasound2t64
          sudo apt-get install -y libxcb-cursor0 xvfb libasound2t64 libpulse0 libgl1-mesa-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          # Оставляем только мультимедиа, SQL уже включен в базу
          modules: 'qtmultimedia'
          setup-python: 'true'

      - name: Configure and Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Run Tests
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            # Проверяем оба возможных пути для Windows (MSVC или MinGW)
            if [ -f "./build/Release/player_tests.exe" ]; then
              ./build/Release/player_tests.exe
            else
              ./build/player_tests.exe
            fi
          elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            # Запуск через виртуальный дисплей для тестов GUI
            xvfb-run --auto-servernum ./build/player_tests
          else
            # Для macOS
            ./build/player_tests
          fi